### ISSUE TITLE
Users vs Members

### ISSUE THREAD

**Issue by jeff-h** [GawainLynch/bolt-extension-members#2]
Could you explain why this doesn't use the existing "users" and instead adds a new "member" concept?

**Comment by GawainLynch** [comment]
> Could you explain why this doesn't use the existing "users" and instead adds a new "member" concept?

Absolutely. The extensions is designed to fit in with Bolt's security design, and part of that is a solid distinction between front & backend security, authentication wise.

Back in Bolt 1.5.x, an social login plugin was added to the available extensions that shipped with Bolt. When we were porting those extensions to Bolt 2's new format, I rewrote that into what became ClientLogin.  When I was discussing that rewrite we came to the conclusion that ClientLogin should do a single job, and try to do it well.  I had further needs, as I was writing BoltBB for a publishing platform that I run, and needed a "membership" based approach to access control. So this extension was born.

It made a lot of sense in the end. The old publishing platform was on WordPress/bbPress, and the user database a) ended up being **massive** making management of backend users very difficult; b) there was an ugly bug in WordPress/bbPress at one stage (well there are lots, but this one was nasty) that allowed someone with a front end role to get in and change certain settings in the backend, including deleting posts.

**Comment by jeff-h** [comment]
Thanks for the explanation. A couple more questions if you have a moment:

* are members "fieldable"?

* if someone needs to be both a member *and* a backend user, they will need two accounts?

Hope you don't mind but I'm kicking the tyres a bit, looking for a potential Drupal replacement.

**Comment by GawainLynch** [comment]
> are members "fieldable"?

Yes, there is a `bolt_members_meta` table that allows you store additional information/settings for a user. For example, this is how with BoltBB I differentiate a members "forum role".  However, the functionality to add/remove these is up to the extension that accesses the API. But very simple to use.

> if someone needs to be both a member and a backend user, they will need two accounts?

Yes. This goes back to the separation of front and back.

> Hope you don't mind but I'm kicking the tyres a bit, looking for a potential Drupal replacement.

Zero stress. It creates a bit of a trail for others to find :+1:

**Comment by jeff-h** [comment]
Thanks — lots to think through. Loving what I've seen so far, but I need a bit of a mind shift in some areas, I think.
