### ISSUE TITLE
DERRRRPPPP

### ISSUE THREAD

**Issue by CarsonF** [GawainLynch/bolt-extension-members#3]
[MembersController line #121](https://github.com/GawainLynch/bolt-extension-members/blob/master/src/Controller/MembersController.php#L121)

![DERRRRRPPPPP](http://www.reactiongifs.us/wp-content/uploads/2013/11/clapping_joker_batman_dark_knight.gif)

**Comment by GawainLynch** [comment]
Fixed in a55dabc8b1d2c6876592d27b5f89e79cfa8c56d0
