### ISSUE TITLE
Use without Social options

### ISSUE THREAD

**Issue by AvaletDev** [GawainLynch/bolt-extension-members#6]
Can I use this extension without the social support. So only a register and login form?

**Comment by GawainLynch** [comment]
Not yet… The authentication part is handled by ClientLogin, and the version that is tagged right now uses a library that is not compatible with Google/Facebook any longer. So I am in the middle of moving to a new library (and a complete rewrite of the code) that will allow a local OAuth password grant.

**Comment by AvaletDev** [comment]
Alright, looking forward to it:)
